# Generated by Django 3.1.6 on 2021-02-09 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='lastname',
        ),
    ]
